### ISSUE TITLE
No rosdep command in windows10

### ISSUE THREAD

**Issue by dzywater** [cyberbotics/webots_ros2#121]
![122753BB-F063-4C23-B5D1-C3EFBB1DD191](https://user-images.githubusercontent.com/22073470/89507837-a601f580-d7ff-11ea-9163-7abe54d7568a.jpeg)

System: ros2 foxy, windows 10 19041

Build failed!
I didn’t run: rosdep update
Because no this command. How to install rosdep.

**Comment by DavidMansolino** [comment]
ROS2 on Windows is still very experimental, this issue is not directly linked to the webots_ros2 packages.

**Comment by dzywater** [comment]
> ROS2 on Windows is still very experimental, this issue is not directly linked to the webots_ros2 packages.

But why does the readme show installation of webots-ros2 based on ros2 on windows 10

**Comment by omichel** [comment]
Can you give the URL of this README file?

**Comment by dzywater** [comment]
> Can you give the URL of this README file?

Not readme but wiki. As the above picture shows, how to call rosdep update in windows 10?
![image](https://user-images.githubusercontent.com/22073470/89620859-dc547900-d8c2-11ea-9126-754a9d3ba5e8.jpg)

**Comment by omichel** [comment]
Sorry, I need a URL for this, not a screenshot.

**Comment by DavidMansolino** [comment]
This is probably the link: http://wiki.ros.org/webots_ros2#webots_ros2_Package

**Comment by lukicdarkoo** [comment]
@dzywater probably didn't clone the submodules:
```bash
git clone --recurse-submodules https://github.com/cyberbotics/webots_ros2.git
```

We have to fix this on ROS Wiki, and this may be something we need to emphasize in this repo in the README files.

**Comment by omichel** [comment]
> We have to fix this in the ROS Wiki, and this may be something we need to emphasize in this repo in the README files.

@lukicdarkoo: can you take care of this?

**Comment by DavidMansolino** [comment]
FYI, currently I have no more right access anymore to it, I have requested right access again.

**Comment by lukicdarkoo** [comment]
@omichel @DavidMansolino 

I am surprised that I have the right to edit ROS Wiki, changed! I will also add to the repo's README in the next PR

**Comment by dzywater** [comment]
> @omichel @DavidMansolino
> 
> I am surprised that I have the right to edit ROS Wiki (I thought I am not allowed to change it), changed! I will also add to the repo's README in the next PR

Thanks all. It works with ros2 and windows 10
![image](https://user-images.githubusercontent.com/22073470/89658938-bbf7df00-d901-11ea-9e57-389370a7aeb6.jpg)

**Comment by james-yoo** [comment]
@dzywater In my case, 'rosdep update' caused following error:
----------------------------------------------------------------------------------
Add distro "dashing"
ERROR: Rosdep experienced an error: module 'os' has no attribute 'geteuid'
-----------------------------------------------------------------------------------
Do you know how to solve it?
