### ISSUE TITLE
Version 1.0.1, launch error in Ubuntu and windows10

### ISSUE THREAD

**Issue by dzywater** [cyberbotics/webots_ros2#144]
![C36D29D7-1D25-48F0-A5E7-6652DC216DBB](https://user-images.githubusercontent.com/22073470/93740763-b76f5780-fc1d-11ea-9877-45d39586b709.jpeg)
![511C33E7-67EA-43EF-968A-0C05E48DA754](https://user-images.githubusercontent.com/22073470/93740777-bfc79280-fc1d-11ea-9b47-5931c26cb7e6.jpeg)

**Comment by DavidMansolino** [comment]
Where is Webots installed on your system? Is WEBOTS_HOME set?

**Comment by dzywater** [comment]
> Where is Webots installed on your system? Is WEBOTS_HOME set?

Yes. Both WEBOTS_HOME and ROS_WEBOTS_HOME are set.

**Comment by dzywater** [comment]
> Where is Webots installed on your system? Is WEBOTS_HOME set?

Version 1.0.0 are OK. And I compiled version 1.0.0 with option    —packages-skip webots_ros2_desktop

**Comment by omichel** [comment]
Which version of Python do you have on Linux?

**Comment by dzywater** [comment]
> Which version of Python do you have on Ubuntu20.02-python3.8.2, windows10-python3.8.4

**Comment by DavidMansolino** [comment]
Just for the note:

> I compiled version 1.0.0 with option —packages-skip webots_ros2_desktop

This is now useless with version 1.0.1 as this package does not exists anymore.

About your issue, it would be useful if you could check in the log if it says something about which line is causing this issue.

**Comment by dzywater** [comment]
> Just for the note:
> 
> > I compiled version 1.0.0 with option —packages-skip webots_ros2_desktop
> 
> This is now useless with version 1.0.1 as this package does not exists anymore.
> 
> About your issue, it would be useful if you could check in the log if it says something about which line is causing this issue.

No useless lines are found 
![Uploading D0520785-5709-42C2-A398-6E69ACA5E3DC.jpeg…]()

**Comment by dzywater** [comment]
> Just for the note:
> 
> > I compiled version 1.0.0 with option —packages-skip webots_ros2_desktop
> 
> This is now useless with version 1.0.1 as this package does not exists anymore.
> 
> About your issue, it would be useful if you could check in the log if it says something about which line is causing this issue.

No useful lines are found
![4B7682EA-8C63-40B6-9C81-D6DCAB6026CF](https://user-images.githubusercontent.com/22073470/93869607-9df20c80-fcfe-11ea-8460-96f29be222e4.jpeg)

**Comment by dzywater** [comment]
> Just for the note:
> 
> > I compiled version 1.0.0 with option —packages-skip webots_ros2_desktop
> 
> This is now useless with version 1.0.1 as this package does not exists anymore.
> 
> About your issue, it would be useful if you could check in the log if it says something about which line is causing this issue.
I try other examples and ‘can’t mix strings and bytes in path components’ always are printed.

**Comment by lukicdarkoo** [comment]
Please check if the following works for you:
https://github.com/cyberbotics/webots_ros2/issues/145#issuecomment-698236822
