### ISSUE TITLE
ur_e_description: attribution?

### ISSUE THREAD

**Issue by gavanderhoorn** [cyberbotics/webots_ros2#154]
Inspecting the `.urdf` files in [webots_ros2_ur_e_description](https://github.com/cyberbotics/webots_ros2/tree/41522f69288adffbf0f000ccfbd3bef42bf952a1/webots_ros2_ur_e_description) shows a big similarity with the files in [ros-industrial/universal_robot/ur_e_description](https://github.com/ros-industrial/universal_robot/tree/06d8b9e2f5f86aa54f9f2845f11edbc84e2f951e/ur_e_description/urdf).

However, I can't seem to find any mention of the origin of these files, nor any form of attribution.

They also appear to have been re-licensed (to Apache 2 from BSD), or at least there isn't any exception mentioned for those specific files.

We're happy that you find those models useful, and it would be appreciated if you could add a statement somewhere clarifying where they came from, under what license they were made available and who created them.

**Comment by DavidMansolino** [comment]
You're completely right, this is indeed missing.
We will add it!
