### ISSUE TITLE
WebotsNode.cpp should add "mWebotsXMLElement = NULL" before line58

### ISSUE THREAD

**Issue by dzywater** [cyberbotics/webots_ros2#273]
exception happens because of uninitialized  mWebotsXMLElement in WebotsNode::getDeviceRosProperties.
So
(1)WebotsNode.cpp should add "mWebotsXMLElement = NULL" before line58
(2) Or  "tinyxml2::XMLElement *mWebotsXMLElement = NULL;' in WebotsNode.hpp

**Comment by lukicdarkoo** [comment]
Could you please make a PR that fixes the bug?
