### ISSUE TITLE
It may be more efficient and consistent o use "device" param in getDeviceRosProperties function ???

### ISSUE THREAD

**Issue by dzywater** [cyberbotics/webots_ros2#276]
To find a plugin, use:
   mWebotsXMLElement->FirstChildElement("plugin");
   pluginElement = pluginElement->NextSiblingElement("plugin");

So, to find a webots device, use:
   mWebotsXMLElement->FirstChildElement("device") instead of mWebotsXMLElement->FirstChildElement() in line89
   deviceChild->NextSiblingElement("device") instead of propertyChild->NextSiblingElement() in line94

**Comment by lukicdarkoo** [comment]
The efficiency is not a concern in that part of the code, the configuration files are tiny, so the startup time will be almost the same. Error handling is important though.

**Comment by lukicdarkoo** [comment]
I believe we can close this issue
