### ISSUE TITLE
webots_ros2_driver include directory is installed twice

### ISSUE THREAD

**Issue by dzywater** [cyberbotics/webots_ros2#282]
The following two directories have same contents.
   ~\install\include\webots_ros2_driver
   ~\install\include\webots_ros2_driver\webots_ros2_driver

The line137~140 are neither necessary nor useful in ~\webots_ros2_driver\CMakeLists.txt.
install(
 DIRECTORY include/${PROJECT_NAME}
 DESTINATION include/${PROJECT_NAME}
)

**Comment by lukicdarkoo** [comment]
For me, this is not the case:
```
lukic@lcb:~/foxy_ws$ ls install/webots_ros2_driver/include/
webots  webots_ros2_driver
lukic@lcb:~/foxy_ws$ ls install/webots_ros2_driver/include/webots_ros2_driver/
PluginInterface.hpp  plugins  PythonPlugin.hpp  utils  WebotsNode.hpp  webots_ros2_driver
```

**Comment by lukicdarkoo** [comment]
I see, I didn't notice the first time
