### ISSUE TITLE
Windows installation dependencies - rosinstall_generator do not work for ros2_control and ros2_controllers

### ISSUE THREAD

**Issue by BenjaminHug8** [cyberbotics/webots_ros2#303]
**Describe the Bug**
Past in the documentation the following commands were supposed to work to install `ros2_control` and `ros2_controllers`.

```
rosinstall_generator ros2_control ros2_controllers --rosdistro foxy > deps.repos
vcs import src < deps.repos
```
Instead we have to clone them from the `foxy` branch.

**To do**

- [ ] Check if these packages can be installed with rosinstall_generator.

**Comment by lukicdarkoo** [comment]
I tried to make it work a while ago, but it seems there is a ROS bug:
https://github.com/ros2/ros_workspace/pull/21#issuecomment-888062636

Let me give it a second try

**Comment by lukicdarkoo** [comment]
1. Creates an empty `deps.txt` file:
    ```
    rosinstall_generator webots_ros2 --exclude RPP --deps > deps.txt
    ```
2. Includes dependencies even though some of them already exist in `src`:
    ```
    set ROS_PACKAGE_PATH=C:\dev\ros2_foxy
    rosinstall_generator webots_ros2 --exclude RPP --deps > deps.txt
    ```
3. Creates an empty `deps.txt` file:
    ```
    set ROS_PACKAGE_PATH=C:\Users\lukic\ros2_ws
    rosinstall_generator webots_ros2 --exclude RPP --deps > deps.txt
    ```

Looking for a way to exclude ROS 2 core packages and already cloned packages from the `deps.txt` file...

**Comment by lukicdarkoo** [comment]
@BenjaminHug8 Solved, checked the installation procedure now

**Comment by BenjaminHug8** [comment]
Perfect thank you.
