### ISSUE TITLE
hardware_interface not found on Windows 10 Foxy ros2

### ISSUE THREAD

**Issue by chngdickson** [cyberbotics/webots_ros2#304]
**Build Failed upon installing webots_ros2_control**

**ERROR msg**
`Finished <<< webots_ros2_tests [1.94s]
--- stderr: webots_ros2_control
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "Findhardware_interface.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "hardware_interface", but CMake did not find one.

  Could not find a package configuration file provided by
  "hardware_interface" with any of the following names:

    hardware_interfaceConfig.cmake
    hardware_interface-config.cmake

  Add the installation prefix of "hardware_interface" to CMAKE_PREFIX_PATH or
  set "hardware_interface_DIR" to a directory containing one of the above
  files.  If "hardware_interface" provides a separate development package or
  SDK, be sure it has been installed.

Failed   <<< webots_ros2_control [5.81s, exited with code 1]

Summary: 15 packages finished [1min 21s]
  1 package failed: webots_ros2_control
  4 packages had stderr output: webots_ros2_control webots_ros2_driver webots_ros2_msgs webots_ros2_tests
  2 packages not processed`

---

**Steps to Reproduce**
1. build ros2_control and ros2_controllers
`rosinstall_generator ros2_control ros2_controllers --rosdistro foxy > deps.repos`
 `vcs import src < deps.repos`
  `colcon build --merge-install`

2. build the other dependencies
`rosinstall_generator vision_msgs ackermann_msgs control_msgs angles realtime_tools --rosdistro foxy > deps.repos
vcs import src < deps.repos
colcon build --merge install `

3. building webots_ros2_control
`git clone --recurse-submodules -b foxy https://github.com/cyberbotics/webots_ros2.git src/webots_ros2
colcon build --merge install`

**Affected Packages**
List of affected packages:
  - webots_ros2_control

**System**
 - Webots Version: [e.g., R2019b, R2020a revision 1]
 - ROS Version: [ros2 foxy] 
 - Operating System: [Windows 10]
 - Graphics Card: [e.g., NVIDIA GeForce GTX 1070]

**Comment by BenjaminHug8** [comment]
I close this issue has there is no answer. Do not hesitate to reopen this issue in case your problem is yet not solved.
