### ISSUE TITLE
ERROR with webots_ros2_tesla package 

### ISSUE THREAD

**Issue by victorsillerico** [cyberbotics/webots_ros2#307]
**Webots version: 2021 b
ROS 2:  Galactic**

`[ERROR] [lane_follower-3]: process has died [pid 102526, exit code 1, cmd '/opt/ros/galactic/lib/webots_ros2_tesla/lane_follower --ros-args'].`
`[ERROR] [tesla_driver-2]: process has died [pid 102523, exit code 1, cmd '/opt/ros/galactic/lib/webots_ros2_tesla/tesla_driver --webots-robot-name  --webots-node-name webots_driver --ros-args --params-file /tmp/launch_params_seg7h2ns'].`

**Comment by BenjaminHug8** [comment]
I close this issue has there is no answer. Do not hesitate to reopen this issue in case your problem is yet not solved.
