### ISSUE TITLE
`ros2 run webots_ros2_driver driver` exits immediately after launch

### ISSUE THREAD

**Issue by NoeelMoeskops** [cyberbotics/webots_ros2#309]
**Describe the Bug**
Executing `ros2 run webots_ros2_driver driver` exits after < 1 second. I suppose this process needs to be running in order to create ROS topics? Webots is running (2021b, [4_wheels_robot.wbt](https://github.com/cyberbotics/webots/blob/released/projects/samples/tutorials/worlds/4_wheels_robot.wbt) as world) with a robot's controller set to `<extern>`

**Steps to Reproduce**
(followed the [tutorial](https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Create-Webots-Robot))
1. Download [4_wheels_robot.wbt](https://github.com/cyberbotics/webots/blob/released/projects/samples/tutorials/worlds/4_wheels_robot.wbt)
2. Launch Webots and load world
2. Set Robot controller to `<extern>`
2. Launch terminal with ROS2 & source webots ROS (Foxy)
3. execute `ros2 run webots_ros2_driver driver`
4. process quits, sim is at 0:00:000 and nothing happened, `ros2 topic list` shows nothing of interest.

**Expected behavior**
`ros2 run webots_ros2_driver driver` continuously running and `ros2 topic list` showing relevant topics of sensors/actuators of the robot.

**Affected Packages**
List of affected packages:
  - webots_ros2_driver

**Screenshots**
Console log from webots:
```
INFO: Starting extern controller for robot "robot".
INFO: Terminating extern controller for robot "robot".
INFO: Starting extern controller for robot "robot".
```
^ terminating happens when the simulation is stopped. Starting when `webots_ros2_driver` in run.
Console log from `ros2`
```
# ros2 run webots_ros2_driver driver  __log_level:=debug
[INFO] [1634841145.720787621] [robot]: Robot description is not passed, using default parameters.
```
^ exits after log

**System**
 - Webots Version: [R2021b]
 - ROS Version: [Foxy] 
 - Operating System: [Fedora]
 - Graphics Card: [NVIDIA GeForce GTX 1080]

**Comment by BenjaminHug8** [comment]
Hi @NoeelMoeskops, did you managed to launch `ros2 run webots_ros2_driver driver` on Fedora?

**Comment by NoeelMoeskops** [comment]
Hi @BenjaminHug8, running (webots) ROS2 on Fedora is quite cumbersome (as you might have noticed). Other ROS2 packages were also having trouble and don't quite work right out of the box. Therefore, I recommand using an Ubuntu container to run ROS2 in. Either the fedora toolbox or distrobox. This is what I ended up doing, and it saved me a lot of time fiddling with the packages. The integration of these containers works quite well as you don't need to worry about permissions and file locations etc (kinda like using WSL lol). By using a container you also get the additional benefit of installing and updating the packages with apt instead of compiling everything. And if you work in a team it will also be pleasant that everyone has the same development environment :).

**Comment by BenjaminHug8** [comment]
Glad to hear that you managed to find a solution, and thank you for sharing it :)

I will then close your 2 issues but feel free to reopen if necessary!
