### ISSUE TITLE
Interact with the Robot UR- Never returns Goal Succeeded

### ISSUE THREAD

**Issue by LuisYordano** [cyberbotics/webots_ros2#34]
Hi,

I am testing Webots with ROS2, the tutorial universal_robot:

![Selection_240](https://user-images.githubusercontent.com/13818395/66245421-41ec3d80-e6d3-11e9-8d7e-c5782e9d4560.png)

When execute the trajectory :

`ros2 action send_goal /follow_joint_trajectory control_msgs/action/FollowJointTrajectory "{
  trajectory: {
    joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint],
    points: [
      { positions: [-1.01, 0.38, -0.63, -0.88, 0.25, -1.63], velocities: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0], accelerations: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0], time_from_start: { sec: 10, nanosec: 500 } }     
    ]
  }
}"`

The  file **trajectory_follower.py**, never execute this part of the code: :

![Selection_241](https://user-images.githubusercontent.com/13818395/66245558-2d5c7500-e6d4-11e9-993a-ea75cf8862e1.png)

The state is always Goal Accepted and does not change to Goal Succeeded.

Thanks in advance for your answer.

**Comment by DavidMansolino** [comment]
@LuisYordano, thank you for this precise bug report, I can indeed reproduce this.
We will try to understand what is happening and fix it for the next update of the package.
I will let you know here when we found something so that if you want you can test the fix.

**Comment by LuisYordano** [comment]
Ok @DavidMansolino , I wait for the fix to testing the package again.

**Comment by DavidMansolino** [comment]
This should now be fixed in #36, @LuisYordano can you confirm the problem is now fixed?

**Comment by LuisYordano** [comment]
@DavidMansolino , Now the trajectory ends successfully.
