### ISSUE TITLE
webots_ros2_importer has no test to verify the interface

### ISSUE THREAD

**Issue by BenjaminHug8** [cyberbotics/webots_ros2#363]
**Is your feature request related to a problem? Please describe.**
Create test(s) to verify the interface with `URDF2Webots`.

**Comment by BenjaminHug8** [comment]
This might be not necessary in case we deprecate `webots_ros2_importer` in favor of the URDF importer feature with `Ros2Supervisor`.

**Comment by ygoumaz** [comment]
Closing this as importer will be removed from the package.
