### ISSUE TITLE
The publication of "/clock" inside "WebotsNode" should be optional.

### ISSUE THREAD

**Issue by TaoYibo1866** [cyberbotics/webots_ros2#368]
I find that webots_ros2_driver publishes simulation time to "/clock" automatically, and this is fine when only one robot exists. However, when there are multiple robots present, there will be duplication in simulation time publication. May be it is better to make time publication optional?

**Comment by lukicdarkoo** [comment]
This is a good idea, thanks!

**Comment by BenjaminHug8** [comment]
I will take care of that with a new feature I am currently working on (it will add a unique supervisor to each simulation to introduce new commands, so I will make it responsible to publish the "/clock" topic).

**Comment by lukicdarkoo** [comment]
@TaoYibo1866 As a temporary solution, you can remap the `/clock` topic to some dummy name (e.g. `/dummy/clock`) of all robots except one.

**Comment by TaoYibo1866** [comment]
> 

Thank you! That's a good idea.

**Comment by BenjaminHug8** [comment]
PR #395 has been merge in #345. Once this last PR will be merged your issue will be solved on the `develop` branch.

**Comment by BenjaminHug8** [comment]
@TaoYibo1866 #345 has been merged!

I will close this issue as the changes requested here are present in the `develop` branch, but feel free to reopen if needed.
