### ISSUE TITLE
Robot universal launch creates a wrong lidar transform

### ISSUE THREAD

**Issue by stef264** [cyberbotics/webots_ros2#404]
**Describe the Bug**
I'm currently writting a custom driver for a robot and use `self.start_device_manager({})` to automatically produce the ROS topics for the lidar, but the transform of the scan is wrong (see RViz picture)

This is also reproducible with the universal launcher.

**Steps to Reproduce**
1. Create Webots world with a lidar attached to a robot
2. Start Webots simulation with `ros2 launch webots_ros2_core robot_launch.py world:=[PATH_TO_WORLD]/world.wbt`
3. See wrong transform in RViz

**Affected Packages**
List of affected packages:
  - webots_ros2_core

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8891249/155700399-be1b118f-4d03-4bd6-85e3-f01ccdf48037.png)

**System**
 - Webots Version: R2022a
 - ROS Version: Foxy
 - Operating System: Ubuntu 20.04

**Additional context**
I had the same problem a while ago with the default diff_drive_controller but #367 fixed it. Now with the universal launcher i get the same problem. Maybe we need the same fix in ros2_core for universal launch?

**Comment by BenjaminHug8** [comment]
Hi, thank you for raising this issue!

First of all, `webots_ros2_core` is now deprecated in favor of `webots_ros2_driver`. With the change of axis system (FLU) in Webots R2022a, webots_ros2_driver has been updated to work with this new version of Webots but not webots_ros2_core.

I suggest you to make the transition to webots_ros2_driver. All the examples on this repository are now using this package.

Once it is done let me know if you are still facing issue with the lidar.

**Comment by BenjaminHug8** [comment]
Hi @stef264, is your issue solved?

**Comment by stef264** [comment]
> Hi @stef264, is your issue solved?

Hi Benjamin, i was out of office last week. I'm currently looking into it.

**Comment by stef264** [comment]
I'm trying to port my custom driver into a plugin file, but can't get subscribers to work.

```py
class PluginNipper:
  
    def init(self, webots_node, properties):

        self.robot = webots_node.robot

        # Initialize motors
        self.left_motor = self.robot.getDevice("left_wheel_joint")
        self.right_motor = self.robot.getDevice("right_wheel_joint")

        self.left_motor.setPosition(float('inf'))
        self.right_motor.setPosition(float('inf'))

        self.left_motor.setVelocity(0)
        self.right_motor.setVelocity(0)

        # Unfortunately, we cannot get an instance of the parent ROS node.
        # However, we can create a new one.
        rclpy.init(args=None)
        self.node = rclpy.node.Node('plugin_nipper')
        self.node.get_logger().info(f"Node created")
        self.__publisher = self.node.create_publisher(Float64, 'custom_time', 1)

        self.node.create_subscription(Float64, "/left_wheel_vel", self.left_motor_callback, 1)

    def left_motor_callback(self, msg: Float64):
        velocity = msg.data
        self.node.get_logger().info(f"Set motor left_motor velocity to {velocity}")
        self.left_motor.setVelocity(velocity)

    def step(self):
        self.__publisher.publish(Float64(data=self.robot.getTime()))
```

The callback function never gets called.
Is a plugin file the right spot to create custom subscribers and interact with Webots Node devices (like RotationMotor)?

**Comment by BenjaminHug8** [comment]
> The callback function never gets called.

I guess that your publisher works, thus the plugin is working (not completely, but some parts are ok).

For your subscriber I found it a bit strange to specify the type of the message in the callback. What happens if you simply use:

```
def left_motor_callback(self, msg):
    velocity = msg.data
    self.node.get_logger().info(f"Set motor left_motor velocity to {velocity}")
    self.left_motor.setVelocity(velocity)
```

Otherwise I would also check that something is published on the `/left_wheel_vel` topic (btw shouldn't it be `left_wheel_vel` instead, without the `/`?).

> Is a plugin file the right spot to create custom subscribers and interact with Webots Node devices (like RotationMotor)?

Create a plugin is the way to go if you want to interact with your robot and if the device is not already implemented in the interface.
e.g. I would not create a plugin to only use a RangeFinder, but I would if I am making my own control of motors (so in your case you should use a plugin).

**Comment by stef264** [comment]
> Otherwise I would also check that something is published on the `/left_wheel_vel` topic (btw shouldn't it be `left_wheel_vel` instead, without the `/`?).

`/` and no `/` work the same.

I can get it to work (shows logger output) if i add `rclpy.spin_once(self.node)` to the function `def step(self):` **but** now the simulation runs at 0.00x - 0.05x. So it seems not the right way.

How does node spinning work in Webots ROS plugins?
I will look further into it tomorrow.

Thanks for your help.

**Comment by BenjaminHug8** [comment]
Can you try to replace `rclpy.spin_once(self.node)` by `rclpy.spin_once(self.node, timeout_sec=0)`, like shown in the example of the `Mavic` drone?

**Comment by stef264** [comment]
> Can you try to replace `rclpy.spin_once(self.node)` by `rclpy.spin_once(self.node, timeout_sec=0)`, like shown in the example of the `Mavic` drone?

This works. Thanks.
The Mavic example is definitely the best example for a custom plugin.
