### ISSUE TITLE
getUrdf() from Webots cannot handle a SliderJoint in a Transform node

### ISSUE THREAD

**Issue by RegularTriangle** [cyberbotics/webots_ros2#407]
When I use SliderJoint in the Robot node, the ROS2 package, which used to work properly, will report an error.  I want to know how to solve this problem?
![Snipaste_2022-03-02_20-46-43](https://user-images.githubusercontent.com/59327429/156365839-2dd7eaf5-9cab-48dc-9222-d786f8cf32bb.png)
![Snipaste_2022-03-02_20-43-15](https://user-images.githubusercontent.com/59327429/156365859-4945cf60-7079-40fe-b1cd-eb342d0fffa9.png)

**Comment by RegularTriangle** [comment]
> 
Thank you for your reply, but It seems that changing the DEF for the Transform node can't work. I made the following changes:
![Snipaste_2022-03-03_21-06-23](https://user-images.githubusercontent.com/59327429/156571782-2d9bf023-a6e7-4e52-a3fa-4f8fcccf86e7.png)
And it reports the the same  error as follow:
![Snipaste_2022-03-03_21-04-52](https://user-images.githubusercontent.com/59327429/156572048-4c6389ab-e5ff-459d-a2af-c3bf86c20fde.png)


However, when I move the SliderJoint node from the children of the Transform node to the children of the Robot node , it works properly.
![Snipaste_2022-03-03_21-22-12](https://user-images.githubusercontent.com/59327429/156574359-483e80de-e1ef-4776-86e8-6f2fe9d068bc.png)
![Snipaste_2022-03-03_21-29-27](https://user-images.githubusercontent.com/59327429/156574379-a90c9c5e-e5d7-4cc3-a37d-d2af610aae7c.png)

**Comment by BenjaminHug8** [comment]
If you check the error message, it is talking about a `LIFT_TRANSFORM` missing link and not anymore about a `LIFT` missing link, so the error type is the same but overall the error is not the same.

But it seems you manage to have a solution to your issue.

However it seems that the `exportUrdf()` function used by Webots does not manage the scenario using the `sliderJoint` in a `Transform` node.

**Comment by RegularTriangle** [comment]
> If you check the error message, it is talking about a `LIFT_TRANSFORM` missing link and not anymore about a `LIFT` missing link, so the error type is the same but overall the error is not the same.
> 
> But it seems you manage to have a solution to your issue.
> 
> However it seems that the `exportUrdf()` function used by Webots does not manage the scenario using the `sliderJoint` in a `Transform` node.

Thanks. I have checked the error message and I think it is the same error. I found that the name of the missing node would change to the same as the DEF of the `Transform` node.
![Snipaste_2022-03-04_18-17-15](https://user-images.githubusercontent.com/59327429/156745775-2be2176e-e2ba-4f3f-b1a6-394394058bbd.png)

In a word, a solution to this issue is to avoid using the `SliderJoint` in a `Transform` node.

**Comment by BenjaminHug8** [comment]
Perfect, then your issue is solved right (you managed to use the `SliderJoint`)?

(In case your issue is solved, please do not close this issue. We will keep it to track and fix the use of the `Transform` node.)

**Comment by RegularTriangle** [comment]
`Perfect, then your issue is solved right (you managed to use the SliderJoint)?`
Yes.
`(In case your issue is solved, please do not close this issue. We will keep it to track and fix the use of the Transform node.)`
OK.

**Comment by gStewartAtUpower** [comment]
I think that this bug also applies to HingeJoint objects which are children of Transform objects.

`[robot_state_publisher-3] Error:   Failed to build tree: parent link [slot] of joint [slot_redacted N_joint] not found.  This is not valid according to the URDF spec. Every link you refer to from a joint needs to be explicitly defined in the robot description. To fix this problem you can either remove this joint [slot_redacted N_joint] from your urdf file, or add "<link name="slot" />" to your urdf file.
[robot_state_publisher-3]          at line 225 in /tmp/binarydeb/ros-galactic-urdfdom-2.3.5/urdf_parser/src/model.cpp
[robot_state_publisher-3] Failed to parse robot description using: urdf_xml_parser/URDFXMLParser
[robot_state_publisher-3] terminate called after throwing an instance of 'std::runtime_error'
[robot_state_publisher-3]   what():  Unable to initialize urdf::model from robot description`

----

`                      Transform {
                        translation 0 0 0.2
                        children [
                          HingeJoint {
                            jointParameters HingeJointParameters {
                            }
                            device [
                              RotationalMotor {
                                name "redacted M"
                              }
                            ]
                            endPoint Slot {
                              type "vehicle wheel"
                              endPoint TractorFrontWheel {
                                name "redacted N"
                                tireRadius 0.2
                                width 1.1
                                physics NULL
                              }
                            }`
                          
Can @RegularTriangle help clarify and establish the last known-good version before this bug began to occur? (regarding the "which used to work properly" comment)

**Comment by ygoumaz** [comment]
This issue was fully fixed in https://github.com/cyberbotics/webots/pull/5899.
