### ISSUE TITLE
URDF importer ideas/suggestions

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots_ros2#409]
I have just tested the URDF importer and I believe there are a few potential ideas and improvements to consider.

- The UR launch files `robot_world_launch.py` and `robot_nodes_launch.py` should be merged into one. It is more user-friendly and it is uncommon that those files are separated. In addition, the `robot_moveit_nodes_launch.py` can be also merged with and the MoveIt nodes should be enabled with the `rviz:=true` launch argument.
- The UR model in RViz should be the same as the UR model in the simulation, the `moveit_ur5e_description.urdf` file should be deleted. That would make the RViz visualization more accurate and less code will be necessary.
- Why the URDF importer is available only in the `develop` branch? I tested it with Webots R2022a and it works fine.
- Maybe `webots_ros2_driver/driver` and `URDFSpawner` could be exposed as a single launch file so it is easier for users.

**Comment by BenjaminHug8** [comment]
Hi @lukicdarkoo, thank you for these ideas!

>     * The UR launch files `robot_world_launch.py` and `robot_nodes_launch.py` should be merged into one. It is more user-friendly and it is uncommon that those files are separated. In addition, the `robot_moveit_nodes_launch.py` can be also merged with and the MoveIt nodes should be enabled with the `rviz:=true` launch argument.

The idea here with 2 launch files is that one is creating the simulation world and the other is here to spawn a robot at anytime. Another scenario could be to start the world and then use multiple other launch files to spawn robots at different moments (maybe some king of tournament for example).

>     * The UR model in RViz should be the same as the UR model in the simulation, the `moveit_ur5e_description.urdf` file should be deleted. That would make the RViz visualization more accurate and less code will be necessary.

That's true!

>     * Why the URDF importer is available only in the `develop` branch? I tested it with Webots R2022a and it works fine.

It has been decided that fixes will target `master` and features target `develop`. These two branches are synchronized with `master` and `develop` of `Webots`.

 Maybe it would be interesting to have a `master` branch for bug fixes and a `develop` branch for features synchronized with the `master` branch of `Webots`, and beside another branch `webots-develop` that is synchronized with the `develop` branch of `Webots`.

>     * Maybe `webots_ros2_driver/driver` and `URDFSpawner` could be exposed as a single launch file so it is easier for users.

Totally agree, that is already something I think about!

**Comment by ygoumaz** [comment]
Closing this issue for now. Feel free to reopen if needed.
