### ISSUE TITLE
Tiago example:Slam can't work

### ISSUE THREAD

**Issue by discleave** [cyberbotics/webots_ros2#424]
**Describe the Bug**
'TIAGo SLAM' in 'TIAGo Example' can't build the map

**Steps to Reproduce**
1. execute 'ros2 launch webots_ros2_tiago robot_launch.py rviz:=true slam:=true'
2. See error 'No map recieived' in rviz
3. execute 'ros2 run teleop_twist_keyboard teleop_twist_keyboard'
4. See error. I can control TIAGo by keyboard, but the map can't be built

**Expected behavior**
I could control TIAGo to build a map.

**Screens
![2022-03-29 09-05-28屏幕截图](https://user-images.githubusercontent.com/49744208/160512000-f080b7dc-b56b-4adb-a443-7949eeaf3771.png)
![error2](https://user-images.githubusercontent.com/49744208/160510401-a60f5069-fd7b-42a9-bb1b-3ca85880bb78.png)

**System**
 - Webots Version: 2022a
 - ROS Version:foxy
 - Operating System: Ubuntu 20.04.3

**Comment by ad-daniel** [comment]
Personally it appears to be working for me, the map topic is published for me, but I do have the LaserRangeScan warning you mention. Did you follow the install procedure described here? https://github.com/cyberbotics/webots_ros2/wiki/Build-and-Install

**Comment by ygoumaz** [comment]
I am closing this issue. Feel free to reopen if needed.
