### ISSUE TITLE
ROS2 Eloquent Release

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots_ros2#44]
ROS2 Eloquent is going to be released very soon. We should support it as soon as possible:
  - [x] Support of `control_msgs` on eloquent: ros-controls/control_msgs#37
  - [x] Extension of the test suite.
  - [x] New release with ROS2 eloquent.

**Comment by DavidMansolino** [comment]
First blocking step almost achieved: ros/rosdistro#23170

**Comment by DavidMansolino** [comment]
Eloquent release done:
  - https://github.com/ros/rosdistro/pull/25519

Foxy release done:
  - https://github.com/ros/rosdistro/pull/25521

**Comment by lukicdarkoo** [comment]
Maybe we could include `webots_ros2` from `develop` branch to ROS 2 Rolling Ridley:
https://www.ros.org/reps/rep-2002.html

> The Rolling distribution of ROS 2 serves as a staging area for future stable distributions of ROS 2 and as a collection of the most recent development releases.

Here is the relevant `distribution.yaml`:
https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml

**Comment by DavidMansolino** [comment]
Yes good idea, but the first thing to do is to enable the tests for rolling ridley

**Comment by DavidMansolino** [comment]
Foxy just officially released: https://discourse.ros.org/t/new-packages-and-patch-release-for-ros-2-foxy-fitzroy-2020-07-10/15348
