### ISSUE TITLE
How to install tiago++ in webots_ros2?

### ISSUE THREAD

**Issue by adminzone24** [cyberbotics/webots_ros2#449]
**Documentation page(s) concerned**
https://cyberbotics.com/doc/guide/tiagopp
https://github.com/cyberbotics/webots_ros2/tree/master/webots_ros2_tiago

**What is the problem with the current documentation?**
In the video, Tiago++ can be installed in webots_ros2, via ros2 launch webots_ros2_tiago tiago.launch.py command. But I can't find tiago.launch.py in webots_ros2/tiago or in webots/tiago++.

**Affected Packages**
List of affected packages:
  - webots_ros2

**System**
 - Webots Version: webots_ros2
 - ROS Version: foxy
 - Operating System:  Ubuntu 20.04

**Comment by ygoumaz** [comment]
Closing this because it is outdated. Feel free to reopen if you still encounter issues with the Tiago.
