### ISSUE TITLE
Problem in instalation 

### ISSUE THREAD

**Issue by Jaylton** [cyberbotics/webots_ros2#454]
When I run: 
`sudo apt-get install ros-$ROS_DISTRO-webots-ros2`
I got this error:
E: Unable to find package ros-foxy-webots-ros2

What should I do?
Thanks.

**Comment by ad-daniel** [comment]
Works for me, did you add the ROS2 repository first? Following this procedure: https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html
