### ISSUE TITLE
getThrottle not working

### ISSUE THREAD

**Issue by ahartlba** [cyberbotics/webots_ros2#460]
Situation:
- I want to drive a car using a gamepad. The commands should be similar to common racing games, meaning shoulder buttons to accelerate/decelerate, left stick to steer A-button to shift up, B-button to shift down.
- The remapping is done by using ros2-galactic

Problem:
- using setThrottle() does not work. Interestingly setGear(), setSteeringAngle(),... all work.
- the throttle value is correctly set (controlled by logging getThrottle()), but the vehicle does not move (of course with a gear and no brakes)
- driving the vehicle with setCruisingSpeed() does work without any problems
- tested multiple vehicles in multiple worlds, every time setCruisingSpeed worked, setThrottle did not

Environment:
- Webots 2022a
- ros2 galacitc
- vehicle to steer (BMW X5 PROTO)

Possible Error
- BUG in bridge

Used Driver Code (Minimal Example which does not work):

```python
import rclpy
class MinimalDriver:
    def init(self, webots_node, properties):
        self.__robot = webots_node.robot

        # ---- ROS Interface ---- #
        rclpy.init(args=None)
        self.__node = rclpy.create_node('minimal_driver')

    def step(self):
        rclpy.spin_once(self.__node, timeout_sec=0)

        self.__robot.setGear(1)
        self.__robot.setThrottle(0.5)
        self.__robot.setBrake(0.0)
        self.__robot.setSteeringAngle(0.0)
```

**Comment by ad-daniel** [comment]
Hi, thank you for the detailed report. I think you are right, something seems to be wrong with the bridge. It's very odd that the other functions of the driver library work, but setting the throttle doesn't, especially considering it does work using a non-ros controller. I'll investigate it

**Comment by ad-daniel** [comment]
The issue is that since the driver library has its own step function, you need to explicitly call it with `self.__robot.step()`. Doing so will call `wbu_driver_step` which will take care of computing the output torque based on the throttle/gear. The reason it velocity control worked is because `wbu_driver_set_cruising_speed` sets the motor velocity directly, and in this case a normal robot step is sufficient

**Comment by ahartlba** [comment]
Thank you, it works now!
