### ISSUE TITLE
Documentation of <webots> tags and it's children like <children> does not exist

### ISSUE THREAD

**Issue by PymZoR** [cyberbotics/webots_ros2#560]
In the turtlebot example https://github.com/cyberbotics/webots_ros2/blob/b2e7635ecfddcb06ecd84e4ea1e7a0f7a0281385/webots_ros2_turtlebot/resource/turtlebot_webots.urdf#L3

the `<webots>` tag along with `<device><ros>[...]</ros></device>` are used, with no documentation associated. It would be great to have all the different parameters and devices available documented.

**Comment by ygoumaz** [comment]
They are now completely documented here: https://github.com/cyberbotics/webots_ros2/wiki/References-Devices.

They are also referenced from the official ROS 2 documentation in this tutorial (task 1): https://docs.ros.org/en/rolling/Tutorials/Advanced/Simulators/Webots/Setting-Up-Simulation-Webots-Advanced.html
