### ISSUE TITLE
The Documentation workflow is always failing

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots_ros2#595]
See https://github.com/cyberbotics/webots_ros2/actions/workflows/documentation.yml
Do we really need it?

**Comment by ad-daniel** [comment]
I'm not familiar with this workflow, as far as I can tell this was used at some point to generate the github wiki based on the contents of `docs` (removed in https://github.com/cyberbotics/webots_ros2/pull/525). The contents referred to webots_ros2_core which has been deprecated and removed, so I suspect it was used then. Does that ring any bell?

Currently I don't believe we rely on it in any way, so I think we can remove it too unless I'm missing something

**Comment by omichel** [comment]
OK, so I would suggest that we remove it.
