### ISSUE TITLE
Controller on Humble not found

### ISSUE THREAD

**Issue by lmartinez-sony** [cyberbotics/webots_ros2#607]
**Describe the Bug**
I have an error with libController.so on humble:

`[driver-5] /opt/ros/humble/lib/webots_ros2_driver/driver: error while loading shared libraries: libController.so: cannot open shared object file: No such file or directory`

I tried with epuck and the ur5, in both cases after the robot is spawn the clock freeze and does not advance anymore.

**Steps to Reproduce**
With epuck
```
apt install ros-humble-webots-ros2-epuck
ros2 launch webots_ros2_epuck robot_launch.py
```

With UR5
```
apt install ros-humble-webots-ros2-universal-robot
ros2 launch webots_ros2_universal_robot robot_world_launch.py
ros2 launch webots_ros2_universal_robot robot_nodes_launch.py
```

**Screenshots**
![Screenshot from 2023-01-26 07-33-23](https://user-images.githubusercontent.com/115515800/214814890-b57aa06e-b93f-485e-835e-88e9e62d1213.png)

**System**
 - Webots Version: R2023a 
 - ROS Version: Humble
 - Operating System: Linux Ubuntu 22.04
 - Graphics Card: GeForce GTX 1660 Ti Mobile, Driver Version: 515.86.01, CUDA Version: 11.7

**Comment by ad-daniel** [comment]
This is a known issue (https://github.com/cyberbotics/webots_ros2/issues/567) which has been addressed already with the release of 2023.0.1. Unfortunately the humble sync has not yet occurred and therefore the patched version is not yet available. Until then you can either install webots_ros2 from [sources](https://github.com/cyberbotics/webots_ros2/wiki/Linux-Installation-Guide) (and uninstalling it from apt) or you can bypass the issue by adding the missing path to LD_LIBRARY_PATH:
`os.environ['LD_LIBRARY_PATH'] += ':/opt/ros/humble/lib/controller'` 

Feel free to reopen the post if problems persist
