### ISSUE TITLE
 [driver-6]: process has died [pid 33255, exit code 1  when lanuch webots_ros2_turtlebot

### ISSUE THREAD

**Issue by HaoLiuHust** [cyberbotics/webots_ros2#619]
**Describe the Bug**
when I lanuch the turtlebot example, there is an error:
```
[ERROR] [driver-6]: process has died [pid 33255, exit code 1, cmd '/root/ros/ros2_ws/install/webots_ros2_driver/lib/webots_ros2_driver/driver --ros-args --params-file /tmp/launch_params_cbkel_rz --params-file /root/ros/ros2_ws/install/webots_ros2_turtlebot/share/webots_ros2_turtlebot/resource/ros2control.yml -r /diffdrive_controller/cmd_vel_unstamped:=/cmd_vel'].
```

**Steps to Reproduce**

**Expected behavior**

**Affected Packages**
List of affected packages:
  - webots_ros2_A
  - webots_ros2_B

**Screenshots**

**System**
 - Webots Version: R2023a
 - ROS Version: foxy
 - Operating System: ubuntu 20.04
 - Graphics Card: [e.g., NVIDIA GeForce RTX 2080 11 GB, AMD Radeon RX 580 8GB, etc.]

**Additional context**

**Comment by ygoumaz** [comment]
What version of the package are you using? Is it installed from sources or from the official repository? Are other examples working or crashing too?

**Comment by HaoLiuHust** [comment]
I am install it from  the official repository, and tried from sources, not works...finally, I install ros2 humble, it works
