### ISSUE TITLE
How to add a new sensor to plugins?

### ISSUE THREAD

**Issue by angel-ayala** [cyberbotics/webots_ros2#627]
Hi, 
I was wondering how can add a new node type to activate under the `<device>` tag in the URDF file.
Looking in the repository, I found that is required to create a plugin file in [include](https://github.com/cyberbotics/webots_ros2/tree/master/webots_ros2_driver/include/webots_ros2_driver/plugins/static) and [src](https://github.com/cyberbotics/webots_ros2/tree/master/webots_ros2_driver/src/plugins/static) folders.

I'm interested in using the [Emitter](https://www.cyberbotics.com/doc/reference/emitter) and [Receiver](https://www.cyberbotics.com/doc/reference/receiver) nodes.
Can you give some guidance to include this?
 
Thank in advance

**Comment by omichel** [comment]
Thank you for this interesting question. Please ask it on https://robotics.stackexchange.com with the `webots` tag as the answer will be more visible there and may be useful to others. I am closing this issue for now to avoid any duplicate.
