### ISSUE TITLE
Drop slam-toolbox for other more robust packages

### ISSUE THREAD

**Issue by ygoumaz** [cyberbotics/webots_ros2#635]
The slam-toolbox package is used in the [Tiago tutorial](https://github.com/cyberbotics/webots_ros2/wiki/Example-TIAGo) for SLAM. There have been reports that the package can be inaccurate when used with the diff-drive controller (see https://github.com/cyberbotics/webots/issues/5540#issuecomment-1371748895). Here is the kind of map generated with the Tiago:

![Screenshot from 2023-02-20 17-23-04](https://user-images.githubusercontent.com/61198661/220158310-076da884-d733-4e4c-a28b-6e8c8d12ea54.png)

As such, I suggest to replace the package with a more accurate alternative like AMCL or Cartographer in the Tiago tutorial. Cartographer is already used in the [Turtlebot tutorial](https://github.com/cyberbotics/webots_ros2/wiki/SLAM-with-TurtleBot3). @delihus has also demonstrated that AMCL gives better results, in the scope of a project using the ROSbot.

The plan is to transfer tutorials to the official ROS 2 documentation. If there is no opposition, slam-toolbox will be replaced by another package in the new Tiago tutorial.

**Comment by delihus** [comment]
I think you should support slam-toolbox. This is the most common and most popular mapping package in ROS2. It is also described on [navigation2_tutorials](https://github.com/ros-planning/navigation2_tutorials/).

Nevertheless I will prepare demo with the ROSbot2 and ROSbot XL with [a dockerized cartographer](https://github.com/husarion/cartographer-docker).

**Comment by delihus** [comment]
There is one tricky way to get work with slam_toolbox is to disable scan_matching. But it is not satisfactory way to fix this.

I described the slam_params [here](https://github.com/husarion/rosbot-xl-mapping/blob/add-webots/config/slam_toolbox_params_webots.yaml).

There are the results:
webots world 
![webots_map](https://user-images.githubusercontent.com/109142865/222102045-e08ab6a3-f20e-446b-802c-66b341cee538.png)
RViz map
![Screenshot from 2022-12-06 15-21-57](https://user-images.githubusercontent.com/109142865/222102100-0a9bec82-c821-473a-9c87-1a259ed6a79c.png)

**Comment by ygoumaz** [comment]
Thanks, I will try this out!

**Comment by lukicdarkoo** [comment]
Tiago odometry is not calibrated, it is probably the main cause of the poor mapping performance

**Comment by ygoumaz** [comment]
The change to Cartographer is now merged and works fine, even without additional odometry calibration. I will try the parameters provided by @delihus with ST to see if I can get any improvements.

@lukicdarkoo, do you have any resources on how to calibrate the odometry? Should it be done using the `diff_drive_controller` package?

If I can get good results using Slam Toolbox, maybe providing the possibility to use both packages to the user would be great.

**Comment by lukicdarkoo** [comment]
> @lukicdarkoo, do you have any resources on how to calibrate the odometry? Should it be done using the diff_drive_controller package?

You can do it with those two steps:
- Move the robot forward, check whether the robot overshoots or undershoots (compare the passed distance from the Odometry message and in Webots), and calibrate the diameter accordingly. Repeat this step until the Odometry and Webots distance have a big difference.
- Rotate the robot in place, check whether the robot overshoots or undershoots, and calibrate the distance between the wheels accordingly. Repeat this step until the Odometry and Webots yaw have a big difference.

The wheel distance and diameter are here:
https://github.com/cyberbotics/webots_ros2/blob/f35554ba57b02a167c72ef3240e2108ff4c0e9ad/webots_ros2_tiago/resource/ros2_control.yml#L16-L17

**Comment by delihus** [comment]
Thinking back to this issue it reminded me I used [EKF](https://github.com/husarion/webots_ros2/blob/master/webots_ros2_husarion/webots_ros2_husarion/resource/ekf.yaml) `robot_localization` to create this maps. 
https://github.com/cyberbotics/webots/issues/5540#issuecomment-1348094887
It doesn't really seem like the issue is odometry.

**Comment by ygoumaz** [comment]
Are you talking about the maps on this thread or in https://github.com/cyberbotics/webots/issues/5540#issuecomment-1348094887? Were you using SLAM Toolbox for the ones with the Husarion logo?

**Comment by delihus** [comment]
I'm talking about this linked map https://github.com/cyberbotics/webots/issues/5540#issuecomment-1348094887 but this is the map which you prepared for ROSbot demo. This is a map of the office with the computers.
![image](https://user-images.githubusercontent.com/109142865/224958199-efc27805-d6ad-4910-b613-3a758c305712.png)

**Comment by delihus** [comment]
Yes but this map is made without position correction. It is just mapping without localization.

**Comment by ygoumaz** [comment]
I calibrated the TIAGo odometry and restored SLAM Toolbox in #676. It works well without scan-matching but ends up drifting after some time. Scan-matching really doesn't work, so I opened an issue on the Github repository: https://github.com/SteveMacenski/slam_toolbox/issues/586.
