### ISSUE TITLE
No such file or directory: 'webots_version.txt'

### ISSUE THREAD

**Issue by RDaneelOlivav** [cyberbotics/webots_ros2#64]
colcon build --symlink-install

When compiling in ROS2 eloquent.
Any ideas?

Starting >>> webots_ros2_desktop
--- stderr: webots_ros2_desktop
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    with open('webots_version.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'webots_version.txt'
---
Failed   <<< webots_ros2_desktop	[ Exited with code 1 ]
[Processing: webots_ros2_desktop]

**Comment by RDaneelOlivav** [comment]
It was the WEBOTS_HOME wasnt set

**Comment by DavidMansolino** [comment]
Thank you for the feedback.
