### ISSUE TITLE
typo in Tutorial Creating a Custom Cpp Plugin document

### ISSUE THREAD

**Issue by RamCharanThota** [cyberbotics/webots_ros2#644]
**Documentation page(s) concerned**
Link to the concerned page.
https://github.com/cyberbotics/webots_ros2/wiki/Tutorial-Creating-a-Custom-Cpp-Plugin

**What is the problem with the current documentation?**
In the " Plugin C++ Implementation File" code section. In the following line

 cmd_vel_subscription_ = node->create_subscription<geometry_msgs::msg::TwistStamped>("/cmd_vel_plugin",
                                                                                       rclcpp::SensorDataQoS().reliable(),
                                                                                       std::bind(&MyRobotDriverPlugin::cmd_vel_callback, 
                                                                                       this, _1));
there is no MyRobotDriverPlugin::cmd_vel_callback function and its throwing error while building the given example.

**Describe how you would fix it**
I think "MyRobotDriverPlugin::cmd_vel_callback" function in the std::bind function should be replaced by "WebotsRos2PluginExample::cmd_vel_callback". so, the correct code would be 
cmd_vel_subscription_ = node->create_subscription<geometry_msgs::msg::TwistStamped>("/cmd_vel_plugin",
                                                                                       rclcpp::SensorDataQoS().reliable(),
                                                                                       std::bind(&WebotsRos2PluginExample::cmd_vel_callback, 
                                                                                       this, _1));

**Comment by ygoumaz** [comment]
You are right! I just fixed it. Thanks for reporting this.
