### ISSUE TITLE
ros2 and webots did not connect with each in tutotial "Setting up a robot simulation (Webots)"

### ISSUE THREAD

**Issue by zilong-ding** [cyberbotics/webots_ros2#675]
![image](https://user-images.githubusercontent.com/71497754/225184139-a295e707-a4c7-4c8e-ac09-8866f54c1fc8.png)
I follow the tutotial step by step,and launch the ros2 launch file,and then pub the topic as below 
![image](https://user-images.githubusercontent.com/71497754/225184450-6f687a25-4d94-4342-9908-c009e93604e9.png)
but the webots has no response,I donot know why?
because the examples on webots_ros2 run correctly

**Comment by ygoumaz** [comment]
On the screen you sent, the supervisor doesn't seem to be connected, preventing the simulation from running. Are you talking about the tutorial in the official documentation of ROS2? In the tutorial, we removed the Ros2Supervisor, so it shouldn't be present in your Webots world.

**Comment by zilong-ding** [comment]
yes,it is the tutorial in the ros2-foxy official documentation,and i do follow the tutotial without any changes.
I open the my_world.wbt by webots open world,and the Ros2Supervisor did not appear,then I relaunch the launch file,and find the webots opens a world file in the dir tmp,and in the end of this file,I found Ros2Supervisor,but my_world.wbt does not have  Ros2Supervisor,it seems that when webotlaunch loads my_world.wbt,it automaticly adds the ROS2Supervisor

**Comment by zilong-ding** [comment]
I read the code of webots turtlebot,and I found it's launch file has ros2supervisor,and I change my my_package launch file likes below
![image](https://user-images.githubusercontent.com/71497754/225521582-ee5d8011-3dd4-48ac-a2c4-69f5aea6da7d.png)
and finally,it moves!

**Comment by ygoumaz** [comment]
By adding the `ROS2SupervisorLauncher()`, you indeed spawn the node that connects to the supervisor in the world and it allows to simulation to run properly. However this is not in the tutorial, because we changed the way the supervisor is spawned. This means that you may not have the latest version of the package. Be sure to install `webots_ros2` **2023.0.2** to benefit from all latest features.
