### ISSUE TITLE
ros2_control HWI for imu_sensor_broadcaster

### ISSUE THREAD

**Issue by delihus** [cyberbotics/webots_ros2#681]
**Is your feature request related to a problem? Please describe.**
It would be great when the IMU sensors could be implemented as Ros2ControlSystemInterface

**Describe the solution you'd like**
In ROSbots we use [rosbot_imu_sensor](https://github.com/husarion/rosbot_hardware_interfaces/blob/main/src/rosbot_imu_sensor.cpp) and [imu_sensor_broadcaster](https://github.com/ros-controls/ros2_controllers/tree/master/imu_sensor_broadcaster).

It will be great to implement IMU as much as ros2_control e.q.
```xml
<ros2_control name="imu" type="sensor">
            <hardware>
               <plugin>webots_ros2_control::Ros2ControlIMU</plugin>
            </hardware>
            <sensor name="imu">
                <state_interface name="orientation.x" />
                <state_interface name="orientation.y" />
                <state_interface name="orientation.z" />
                <state_interface name="orientation.w" />
                <state_interface name="angular_velocity.x" />
                <state_interface name="angular_velocity.y" />
                <state_interface name="angular_velocity.z" />
                <state_interface name="linear_acceleration.x" />
                <state_interface name="linear_acceleration.y" />
                <state_interface name="linear_acceleration.z" />
            </sensor>
        </ros2_control>
```

Best regards,
Jakub

**Comment by ygoumaz** [comment]
We support the IMU sensor through the corresponding `webots_ros2_driver` plugin: [Ros2IMU](https://github.com/cyberbotics/webots_ros2/blob/master/webots_ros2_driver/src/plugins/dynamic/Ros2IMU.cpp). It allows to interface 3 different Webots sensors (accelerometer, gyro and inertial unit) with ROS 2. Orientation, velocity and acceleration is published to the IMU topic.

We are not planning to use the `ros2_control` package to interface IMUs. But feel free open a contribution if you want/need to implement it (or add it to your current #682 PR if needed by the new ROSbot example). We would be happy to review your contribution.

**Comment by ygoumaz** [comment]
Closing as we won't fix. Feel free to reopen if you have any remarks.
