### ISSUE TITLE
Multiple trajectory controllers cannot all start successfully

### ISSUE THREAD

**Issue by cdlycode** [cyberbotics/webots_ros2#707]
My environment: 
	Ubuntu version: 20.04
	Webots version: R2022a
	ROS2 version: rolling

I have a robotic arm model with multiple joints defined, and according to the official example, I successfully ran my robot. At the beginning, I entrusted all the joints to a trajectory controller for management, which worked very well. Later on, it was necessary to split the joints to meet the needs of different controllers to manage different joints. 

I split 21 trajectory controllers in the `ros2_control_configuration.yml` configuration file and used the same `spawner.py` script to pull up the controllers in the `launch.py` file. However, each time I started, several controllers failed to pull up, and it was random.

I wrote this in the `launch.py` file

```py
    aaa_trajectory_controller_spawner = Node(
        package='controller_manager',
        executable='spawner',
        output='screen',
        prefix=controller_manager_prefix,
        arguments=['aaa_joint_trajectory_controller'] + controller_manager_timeout,
    )
    
    bbb_trajectory_controller_spawner = Node(
        package='controller_manager',
        executable='spawner',
        output='screen',
        prefix=controller_manager_prefix,
        arguments=['bbb_joint_trajectory_controller'] + controller_manager_timeout,
    )
    ...
    ...
```

After testing, when 13 trajectory controllers are activated simultaneously, all can be successfully pulled up, and after exceeding 13, there will be a random failure situation.

I don't know if this is a bug, I hope to get your help!

**Comment by ygoumaz** [comment]
I am closing this issue for now, feel free to reopen if needed.
