### ISSUE TITLE
Camera Feedback Not Displayed in Tiego_Iron Simulation

### ISSUE THREAD

**Issue by animesh-singhal** [cyberbotics/webots_ros2#735]
**Bug Description**
The camera feedback and display screen in the Tiego_Iron simulation are not functioning as expected. Instead of showing the relevant content, both the camera and the display screen remain black throughout the simulation.

**Steps to Reproduce**

1) Visit the following page for reference: [Example-TIAGo](https://github.com/cyberbotics/webots_ros2/wiki/Example-TIAGo)
2) Set up the webots_ros2 package. If you choose to install via binaries, please note that a few dependencies will not be automatically installed, which can result in errors during the colcon build process.
3) Install the ros-humble-slam-toolbox package by running the following command: sudo apt install ros-humble-slam-toolbox.
4) Launch the scene using the following command: ros2 launch webots_ros2_tiago robot_launch.py rviz:=true slam_toolbox:=true.

**Affected Packages**
List of affected packages:
  - webots_ros2_tiago

**Screenshots**
Screenshot attached
![Screenshot from 2023-05-08 23-43-16](https://user-images.githubusercontent.com/67463887/236903535-cbcae0c4-91d7-4113-85e0-c96fbf84a39d.png)

**System**
 - Webots Version: [latest]
 - ROS Version: [Humble]
 - Operating System: [Ubuntu Jammy]

**Comment by ygoumaz** [comment]
The camera and display are not intended to be used in this simulation. In consequence, they are not enabled by the ROS 2 controller node. This is why the overlays are not updated. 

If you installed the package from sources, you can enable the camera by adding the following tags to the `tiago_webots.urdf` file and rebuild the package with `colcon build`.

```xml
<device reference="camera" type="Camera">
  <ros>
    <enabled>true</enabled>
    <alwaysOn>true</alwaysOn>
  </ros>
</device>
```

However, it is not a good idea to show these overlays if the devices stay disabled. I will make a PR to remove those.
