### ISSUE TITLE
libhardware_interface.so Issue when colcon build for webots_ros2_control

### ISSUE THREAD

**Issue by jainishmehta** [cyberbotics/webots_ros2#748]
**Describe the Bug**
![image](https://github.com/cyberbotics/webots_ros2/assets/45054638/c5090ac6-80a6-4472-b006-cb368d21243e)
I am trying to do colcon build for webots_ros2_control.  I did git clone from ros2_control to create a package on ros2 for hardware interface and I get this wierd error similar to https://github.com/ros/class_loader/issues/188 . 

**Steps to Reproduce**
1. Clone from https://github.com/ros-controls/ros2_control for webots_ros2_control. 
2. Do colcon build to get the packages for it.

**Expected behavior**
Should work fine and build properly.

**Screenshots**
![image](https://github.com/cyberbotics/webots_ros2/assets/45054638/9d057fca-e7c3-4d4d-8326-f8715fd80a19)

**System**
 - Webots Version: R2023
 - ROS Version: 2, FOXY (Not sure abut foxy though)
 - Operating System: Ubuntu 20.04 focal

**Comment by jainishmehta** [comment]
HI, This is the issue from webots_ros2_control.
![image](https://github.com/cyberbotics/webots_ros2/assets/45054638/3dc15dc1-5bf7-491f-bb0d-42bb85b110b7)

**Comment by ygoumaz** [comment]
You definitely have a conflict between multiple ROS installations. The issue here is not related to `webots_ros2` but to the `ros2_control` package. I suggest to first clarify what your ROS distro is and install basic packages like `ros2_control` using apt.
```
sudo apt install ros-${ROS_DISTRO}-ros2-control
```

Please do not open multiple issues, you can directly post on #747.

**Comment by jainishmehta** [comment]
Hi, 

![image](https://github.com/cyberbotics/webots_ros2/assets/45054638/ece96ff0-3277-48a7-ae03-8b200e77058b)

The command does not work

**Comment by jainishmehta** [comment]
![image](https://github.com/cyberbotics/webots_ros2/assets/45054638/daec2268-124b-474a-bbcc-a24128e19e6a)
Also, sorry I redid it and it is already installed and still the same error when I do colcon build. I agree the error is in ros2_control, however I can't find a workaround. NOt sure if people can reproduce this bug.
