### ISSUE TITLE
setup.py install is deprecated

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots_ros2#776]
When installing from sources (develop brach) and compiling with ROS2 Iron I get this deprecation error for most of the modules
```
--- stderr: webots_ros2_importer                                                                
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
```

**Comment by omichel** [comment]
This is a known ROS 2 issue which should be fixed by disabling the warning. See https://github.com/ament/ament_cmake/issues/382 and https://robotics.stackexchange.com/questions/24230/setuptoolsdeprecationwarning-in-ros2-humble/24349#24349
