### ISSUE TITLE
The "driver" from the tutorials 'cannot connect to Webots instance, retrying for another 35 seconds...' 

### ISSUE THREAD

**Issue by gaileyleseman** [cyberbotics/webots_ros2#807]
**Describe the Bug**
When following the webots tutorials the driver cannot connect to the webots instance and will "give up" after a minute. 

**Steps to Reproduce**
1. Install Webots (debian with apt) according to the steps described [here](https://cyberbotics.com/doc/guide/installation-procedure#installing-the-debian-package-with-the-advanced-packaging-tool-apt)
2. Follow the instructions described [here](https://docs.ros.org/en/humble/Tutorials/Advanced/Simulators/Webots/Setting-Up-Simulation-Webots-Basic.html) to create a robot, world and the ROS package
2. Clone the `webots_ros2` repository in the `src` folder to access the latest version
3. Export the environment variable WEBOTS_HOME=/usr/local/webots
4. Build your packages, source and launch the example with `ros2 launch my_package robot_launch.py`
5. Webots will launch (see screenshot below) but the node will complain about not being able to connect to the instance (see logs below). 

**Expected behavior**
The driver node is able to connect to the Webots instance launched through ROS. 

**Affected Packages**
List of affected packages:
  - webots_ros2

**Screenshots**
![image](https://github.com/cyberbotics/webots_ros2/assets/22048962/8c4b3b37-cfb8-49da-8f34-6c38aed0222a)

**System**
 - Webots Version: R2023b (from debian through apt)
 - webots_ros2 version: 2023.1.0 (built from source)
 - ROS Version: Humble
 - Operating System: Ubuntu 22.04
 - Graphics Card: Nvidia Quadro P1000, Driver Version: 525.125.06   CUDA Version: 12.0

**Additional context**
Logs: 
```
❯ ros2 launch my_package robot_launch.py
[INFO] [launch]: All log files can be found below /home/gailey/.ros/log/2023-07-04-21-47-42-983878-gailey-zbook-11683
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [webots-1]: process started with pid [11684]
[INFO] [driver-2]: process started with pid [11686]
[INFO] [obstacle_avoider-3]: process started with pid [11688]
[driver-2] Cannot connect to Webots instance, retrying for another 50 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 45 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 40 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 35 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 30 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 25 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 20 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 15 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 10 seconds...
[driver-2] Cannot connect to Webots instance, retrying for another 5 seconds...
[driver-2] Giving up...
[ERROR] [driver-2]: process has died [pid 11686, exit code 1, cmd '/opt/ros/humble/lib/webots_ros2_driver/driver --ros-args --params-file /tmp/launch_params_2xstbd9i'].
```

**Comment by ygoumaz** [comment]
Thanks for reporting. The tutorial for Humble is not up-to-date yet, as the package is not synchronized. For the latest version, please checkout other distributions, like Iron or Rolling. If you want to keep the exact same code and files you created with this version of the instructions, you can update your `webots_ros2` sources to the latest commit. A fix to restore backwards compatibility with the old tutorial version was introduced in #805.
