### ISSUE TITLE
Supervisor `animation_start_recording` and `animation_stop_recording` services

### ISSUE THREAD

**Issue by nikolaseu** [cyberbotics/webots_ros2#809]
`Ros2Supervisor` is missing the `animation_start_recording` and `animation_stop_recording` services.

These services are documented in the webots website but seem to be available only for ROS 1.

I'm willing to implement them if there's desire to include them officially. I'm currently checking if it actually works (subclassing Ros2Supervisor).

**Comment by ygoumaz** [comment]
This would be a nice contribution. Feel free to open a PR that includes the new services and the required changes in Ros2Supervisor. Don't forget to edit the changelogs with your new updates. We will be happy to review your PR.
