### ISSUE TITLE
Improve CI Tests

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots_ros2#81]
Currently our CI test is testing the source code, compilation and installation of the packages.

But the behaviour is not tested.
It would be nice to run at least one node in the test and make sure it works correctly.
This way it will be very easy to check if the compatibility with one specific release of ROS is working (instead of testing manually on each supported version).

**Comment by ygoumaz** [comment]
Behavior tests are running already! First test implemented here: https://github.com/cyberbotics/webots_ros2/pull/268.
