### ISSUE TITLE
API and robot description handling changes in CM and RM

### ISSUE THREAD

**Issue by destogl** [cyberbotics/webots_ros2#916]
Hi Webots-Team,

Please be aware of the upcoming changes in CM and RM in ros-controls/ros2_control#1354. We had to make some adjustments for the Gazebo Sim simulator. I have adjusted the changes to CM and RM to make it simpler to use by simulators (at least in the Gazebo case). Check also this integration in ros-controls/gz_ros2_control#365 as it might help you to faster solve the potential upcoming issues.

Cheers,

Dr. Denis

**Comment by lukicdarkoo** [comment]
@destogl This change is not hitting Jazzy, only Rolling?

**Comment by destogl** [comment]
> @destogl This change is not hitting Jazzy, only Rolling?

@lukicdarkoo it will also hit Jazzy. We will be merging soon and then @bmagyar should know when it will be released. 

The reason for this breaking change is that we don't want to keep people for the next 5 years in the dark with some important improvements. And currently Jazzy footprint is still low (presumably)

**Comment by destogl** [comment]
FYI: gazebo fix is here, this might help you with the approach: ros-controls/gz_ros2_control#265
