### ISSUE TITLE
"webots_ros2" package not found

### ISSUE THREAD

**Issue by m-salman-05** [cyberbotics/webots_ros2#961]
**Describe the Bug**
When following the tutorial to install Webots for ROS2 (Jazzy) linked here: https://docs.ros.org/en/jazzy/Tutorials/Advanced/Simulators/Webots/Installation-Windows.html, when I run the following command to install the relevant package,
`sudo apt-get install ros-jazzy-webots-ros2`

The following error comes up. 

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-jazzy-webots-ros2
```

**System**
 - ROS Version: Jazzy
 - Operating System: Using WSL2 on Windows 11. The distro is Ubuntu 24.04.

Is there any way to resolve the issue?

**Comment by lukicdarkoo** [comment]
@m-salman-05 It should be covered by #960
